fragment ImageThumbnailFragment on FileField {
	alt
	basename
	format
	height
	id
	mimeType
	size
	title
	url
	width
	responsiveImage(
		imgixParams: { w: 2000, auto: format }
		sizes: "(max-width: 46.24em) 100vw, 50vw"
	) {
		alt
		aspectRatio
		base64
		bgColor
		height
		sizes
		src
		srcSet
		webpSrcSet
		title
		width
	}
}
