query About {
	about {
		id
		content {
			blocks {
				... on StaffBlockRecord {
					__typename
					id
					people {
						id
						firstName
						lastName
						title
						phone
						email
						image {
							...MediaFragment
						}
					}
				}
			}
			links
			value
		}
		image {
			...MediaFragment
		}
		address
	}
}
