query Overview {
	overview {
		id
		leftColumn {
			__typename
			... on SelectedProjectBlockRecord {
				id
				image {
					...MediaThumbnailFragment
				}
				project {
					...ProjectFragment
				}
			}
		}
		rightColumn {
			__typename
			... on SelectedProjectBlockRecord {
				id
				image {
					...MediaThumbnailFragment
				}
				project {
					...ProjectFragment
				}
			}
		}
	}
}
