query AllProjects($first: IntType = 100, $skip: IntType = 0) {
	allProjects(first: $first, skip: $skip) {
		...ProjectFragment
	}
	_allProjectsMeta {
		count
	}
}

query Project($slug: String!) {
	project(filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

fragment ProjectFragment on ProjectRecord {
	id
	title
	summary
	description {
		blocks
		links
		value
	}
	program
	projectStatus
	year
	size
	commisioner
	credits
	slug
	gallery {
		__typename
		... on MediaRowBlockRecord {
			id
			mediaAsset {
				...MediaFragment
			}
		}
		... on TextRowBlockRecord {
			id
			leftColumn {
				blocks
				links
				value
			}
			rightColumn {
				blocks
				links
				value
			}
		}
		... on ImageAndTextRowBlockRecord {
			id
			image {
				...ImageFragment
			}
			imageRight
			text {
				blocks
				value
				links
			}
		}
	}
}
